default_platform(:ios)

lane :bump_version do
  package_json = load_json(json_path: '../../package.json')
  version = package_json['version']
  increment_build_number(xcodeproj: 'App.xcodeproj')
  increment_version_number(version_number: version, xcodeproj: 'App.xcodeproj')
end
