default_platform(:ios)

lane :bump_version do
  package_json = load_json(json_path: '../../package.json')
  version = package_json['version']
  increment_build_number(xcodeproj: 'App.xcodeproj')
  increment_version_number(version_number: version, xcodeproj: 'App.xcodeproj')
end

def enable_manual_provisioning(project_file, provisioning_profile_uuid)
  UI.message 'Switching to manual code signing'
  fastlane_require 'xcodeproj'
  project = Xcodeproj::Project.open(project_file)
  target = project.native_targets.detect { |target| target.name == 'App' }
  target_attributes = project.root_object.attributes['TargetAttributes']
  target_attributes.each { |_id, attrs| attrs['ProvisioningStyle'] = 'Manual' }
  target.build_configurations.each do |item|
    item.build_settings['PROVISIONING_PROFILE[sdk=iphoneos*]'] = provisioning_profile_uuid
    item.build_settings['DEVELOPMENT_TEAM'] = 'UG77RJKZHH'
    item.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = 'Apple Distribution'
  end
  project.save
end

lane :configure_release_signing do
  if is_ci?
    UI.message 'Configuring signing for App Store release'
    # Use distribution profile for App Store deployment
    provisioning_profile = ENV['APPSTORE_PROVISIONING_PROFILE_UUID']
    enable_manual_provisioning('../App.xcodeproj', provisioning_profile)
  else
    UI.error('This lane should only be run on CI!')
  end
end
